### ISSUE TITLE
Create CI for unit testing

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/DeepClean#5]
Create GitHub workflows like those used in the [GW-IaaS project](https://github.com/fastmachinelearning/gw-iaas/tree/main/.github/workflows) to automate unit testing and force unit tests to pass before PRs can be accepted.

**Comment by RishiKumarRay** [comment]
@alecgunny i would like to go for this ,please tell me the command you use to perform these tests

**Comment by alecgunny** [comment]
Hi @RishiKumarRay. I appreciate your offer to contribute, unfortuantely right now we're trying to limit contributions to scientists from within the International Gravitational-Wave Observatory Network. I've added this stipulation to our `CONTRIBUTING.md` to make this more clear, and will update that document as we widen the net of contributors. Feel free to keep an eye out for this as the repo develops!
